run_name: "1.5b-base-classifier-headinit-64bz-95data-rerun"

model:
  model_name: "Qwen/Qwen2.5-1.5B-Instruct"
  use_llm_head_weights: True
  llm_head_model_name: "Qwen/Qwen2.5-1.5B-Instruct"
  lora_config:
    enabled: False
    r: 32
    alpha: 32
    bias: none
    dropout: 0.01
    target_modules: 
      - v_proj
      - o_proj
      - k_proj
      - v_proj
      - o_proj
      - gate_proj
      - up_proj
      - down_proj

train:
  lr: 0.00005
  epochs: 1
  max_steps: -1 # set to -1 if you want to use epochs instead
  
  batch_size_per_device: 64
  gradient_accumulation_steps: 1
  optimizer: paged_adamw_32bit
  weight_decay: 0.0
  lr_scheduler: "cosine"
  warmup_steps: 128
  grad_clip: 1.0
  gradient_checkpointing: True

logging:
  wandb: True
  logging_steps: 1
  project_name: Sentiments
  entity: kauuu 


seed: 43
defaults:
  - _self_
  - data_settings